name: Deploy Ubuntu Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verificar servidor
        run: |
          echo "======================="
          echo "DEPLOY DESDE GITHUB"
          echo "======================="

          echo "Servidor:"
          hostname

          echo "Usuario:"
          whoami

          echo "Fecha:"
          date

          echo "PWD:"
          pwd

          echo "Contenido:"
          ls -la