name: Test API
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node backend/server.js &
      - run: curl -s http://localhost:3000/tasks | grep "Aprender GitHub Actions"